### PR TITLE
fixed #407

### LINKED ISSUE #407: Vendor Shop page fields selection
Let each vendor show which email they want to display in their shop.

Also, let them select which fields they want to show : https://prnt.sc/f8lZGzQq9ijo

### PR DESCRIPTION
**Pull request by kndnsow**

### CODE REVIEW

**Comment by kndnsow** [comment]
tested

**Comment by Sangi0** [comment]
Test done.

**Comment by cool-raju** [comment]
invaild,
https://developer.wordpress.org/plugins/security/securing-output/
data must sanitize before update to database
@kundandualcube

**Comment by moumitahalder** [comment]
@kundandualcube @Sangi0 any update???

**Comment by moumitahalder** [comment]
review given 4days ago. still no responce why?? @Sangi0 please look into this issue

**Comment by Sangi0** [comment]
tested

**Comment by moumitahalder** [comment]
@kundan are u kidding?

**Pull request closed without merging**
