### PR TITLE
Fixed issue #416 and 1st part done #407

### PR DESCRIPTION
**Pull request by kndnsow**
test done

### CODE REVIEW

**Comment by moumitahalder** [comment]
@cool-raju not working, don't give this update tommorow

**Comment by Sangi0** [comment]
The backend submenus of MultiVendorX are coming as blank pages https://watch.screencastify.com/v/LzE4JiZSddY3XinJugQJ

**Comment by cool-raju** [comment]
thanks @moumitahalder  and @Sangi0 for d update

**Comment by moumitahalder** [comment]
@kundandualcube please check each code and flow thoroughly and carefully before committing the codes.

**Pull request closed without merging**
